import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'center',
      height: '100%',
      width: '100%',
    },
    scrollContainer: {
      paddingBottom: 100,
      width: 390,
      alignItems: 'center',
    },
    eventContainer: {
      width: '93%',
      height: 250,
      marginVertical: 10,
      borderColor: '#000',
      borderWidth: 3,
      borderRadius: 10,
      overflow: 'hidden',
      marginHorizontal: '2.5%',
    },
    backgroundImage: {
      resizeMode: 'cover',
      flex: 1,
      width: '100%',
      height: '100%',
    },
    overlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    eventName: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#ffffff',
      marginBottom: 10,
    },
    eventDetails: {
      fontSize: 16,
      color: '#ffffff',
    },
    editableText: {
      fontSize: 18,
      fontWeight: 'bold',
      backgroundColor: '#fff',
      color: '#000',
      marginBottom: 5,
      width: '90%',
      padding: 5,
      textAlign: 'center',
      borderRadius: 5,
    },
    editButton: {
      position: 'absolute',
      bottom: 10,
      right: 20,
      padding: 15,
      backgroundColor: '#000',
      width: 65,
      height: 65,
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    addButton: {
      position: 'absolute',
      bottom: 20,
      left: '45%',
      transform: [{ translateX: -20 }],
      padding: 15,
      backgroundColor: '#000',
      borderRadius: 50,
      width: 65,
      height: 65,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    deleteButton: {
      position: 'absolute',
      alignItems: 'center',
      top: 10,
      right: 10,
      padding: 5,
      backgroundColor: '#b6292b',
      borderRadius: 50,
      height: 30,
      width: 30,
    },
  });

  export default styles;