import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'flex-start',
      height: '60%',
      backgroundColor: '#000',
    },
    buttonContainer: {
      position: 'absolute',
      bottom: 100,
      width: '100%',
      marginTop: 10,
      paddingTop: 70,
      alignItems: 'center',
    },
    button: {
      width: '90%',
      height: '30%',
      marginVertical: 3,
      backgroundColor: 'rgba(0,0,0,0.7)',
      borderColor: '#b6292b',
      borderWidth: 2,
      borderRadius: 38,
      alignItems: 'center',
      justifyContent: 'center',
    },
    text: {
      color: '#fff',
      fontSize: 40,
      padding: 2,
      textAlign: 'center',
      fontFamily: 'CODE-Light',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#000',
    },
    loadingText: {
      fontSize: 20,
      color: '#B6292B',
      marginTop: 20,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    modalContainer: {
      width: '80%',
      backgroundColor: '#fff',
      borderRadius: 38,
      borderColor: '#000',
      borderWidth: 2,
      padding: 20,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
    },
    input: {
      width: '100%',
      height: 40,
      borderColor: '#ccc',
      borderWidth: 1,
      borderRadius: 38,
      paddingHorizontal: 10,
      marginBottom: 5,
      backgroundColor: '#f9f9f9',
      overflow: 'hidden',
    },
    modalButton: {
      padding: 10,
      backgroundColor: '#b6292b',
      borderRadius: 38,
      width: '100%',
      alignItems: 'center',
      marginBottom: 10,
    },
    modalButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    closeButton: {
      padding: 10,
      backgroundColor: '#000',
      borderRadius: 38,
      width: '100%',
      alignItems: 'center',
    },
    closeButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    forgotText: {
      color: '#b6292b',
      fontSize: 16,
      marginTop: 0,
      marginBottom: 10,
      textDecorationLine: 'underline',
      textAlign: 'right',
    },
    createText: {
      color: '#b6292b',
      fontSize: 16,
      marginTop: 10,
      marginBottom: 0,
      textDecorationLine: 'underline',
      textAlign: 'center',
    },
    notRegisteredText: {
      color: '#999',
      marginTop: 10,
      marginBottom: 0,
    },
    errorText: {
      color: '#b6292b',
      marginBottom: 10,
    },
    passwordContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      height: 40,
      borderColor: '#ccc',
      borderWidth: 1,
      borderRadius: 38,
      paddingHorizontal: 10,
      backgroundColor: '#f9f9f9',
      overflow: 'hidden',
      marginBottom: 5,
    },
    passwordIcon: {
     right: 10,
     position: 'absolute',
     width: '10%',
    },
    passwordInput: {
     position: 'absolute',
     marginLeft: 10,
     width: '90%',
     flex: 1,
    },
  });

  export default styles;